"""Regenerate configs/default.yaml from the code defaults, with each field's reasoning as a comment.

    python scripts/export_config.py
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from pydantic import BaseModel

from drowsiness.config.settings import Settings

OUT = Path(__file__).resolve().parents[1] / "configs" / "default.yaml"


def _fmt(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_fmt(v) for v in value) + "]"
    if isinstance(value, float) and value >= 1e9:
        return "1.0e9"
    if isinstance(value, str):
        return f'"{value}"'
    return str(value)


def render(settings: Settings) -> str:
    lines = [
        "# Driver drowsiness detection - default configuration.",
        "# Generated by scripts/export_config.py from src/drowsiness/config/settings.py.",
        "# These are literature-informed STARTING POINTS, not tuned values.",
        "# Tune on the development split, confirm on validation, never on test.",
        "",
    ]
    for section_name in Settings.model_fields:
        section: BaseModel = getattr(settings, section_name)
        lines.append(f"{section_name}:")
        for name, field in type(section).model_fields.items():
            if field.description:
                for chunk in textwrap.wrap(field.description, 96):
                    lines.append(f"  # {chunk}")
            value = getattr(section, name)
            if isinstance(value, dict):
                lines.append(f"  {name}:")
                for k, v in value.items():
                    lines.append(f"    {k}: {_fmt(v)}")
            else:
                lines.append(f"  {name}: {_fmt(value)}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(render(Settings()), encoding="utf-8")
    print(f"wrote {OUT}")
